markdown: kramdown
highlighter: pygments
permalink: /news/:year/:month/:day/:title/
excerpt_separator: ""
encoding: utf-8

google_analytics_id: UA-63569270-1

bbs_url: http://bbs.fcgvisa.com
help_url:

collections:
  docs:
    output: true

name: 飞出国移民（香港）
description: 飞出国移民（香港）
url: http://flyabroad.com.cn

gems:
  - jekyll-feed
