#!/bin/bash

if [ $# -lt 1 ]
then
        read -p "please input commit message:" desc
else
	echo "comment message = $1"
	repository="$1"
fi

git clone git@github.com:fcg/$repository.git
cd $repository && \
git checkout --orphan gh-pages && \
git rm -rf .